### ISSUE TITLE
Problem running postgis container on Windows 10

### ISSUE THREAD

**Issue by cybernar** [3liz/postgis#3]
Hello, I want to test **3liz/postgis** container separately to figure out how it works.

I have a problem on Windows 10 when I try to set a volume for data on the Windows host. I'm not sure to understand everything with the `postgres` user uid & gid. Please can you help me ?

1) I created an empty folder for the pg data in D:\Docker\postgis_data2

When I try this on Windows :

`docker run --name 3liz_pgis -d -p 5434:5432 -e POSTGRES_PASSWORD=blablagis -v D:\Docker\postgis_data2:/var/lib/postgresql/data 3liz/postgis:13-3`

The container stops immediately with Exited(4) status

In the logs, I have only this : 

```
Changing postgres group id (999) to 0
groupmod: GID '0' already exists
```

2) So, I tried the same with the "official" postgis docker image, and it works :

`docker run --name pgis_pgis -d -p 5433:5432 -e POSTGRES_PASSWORD=blablagis -v D:\Docker\postgis_data:/var/lib/postgresql/data postgis/postgis:13-3.3`

I checked the uid:gid of postgres account in this pgis_pgis container, it is 999:999.

What is happening with **3liz/postgis:13-3** on Windows ? Do I have to change POSTGRES_USER or POSTGRES_UID ?

Regards, Cyril

**Comment by dmarteau** [comment]
The 3liz/postgis container enable you to setup uid/gid dynamically in order to adapt to your local postgres uid/gid if you choose to mount local directories with specific postgres id. 

When you mount a host volume as pg_data volume, the entrypoint will change the postgres uid/gid in order to match those of the volumes (otherwise postgres will not be enable to use that directory). 

This is the opposite of the official postgres/postgis image wich will change the owner of your PG_DATA directory in order to match the internal postgres uid defined in the image - we think that this behavior is not desirable in  production environment.

I don't know how Docker behave on Windows but it appears that your directory is beeing seen with uid/gid 0 - this is the case if your run your container as root and the mounted volume does not exists: docker will  create the directory as root, but since you have precreated your directory this is may be related to how docker on Windows match volumes between the Linux VM and the Windows filesystem.

To fix this you may either:
1. Do nothing, the container will use a dynamically created docker volume.
2. Build the image with predefined POSTGRES_UID/POSTGRES_GID (they are build arguments) in order to match your local uid/gid. You will be able to run your docker container with --user options  (this is the recommended option on Linux) .
3. Use a named docker volume for PG_DATA - also a good solution to get your data persistent.
4. Create pour pg_data directory with the same uid/gid as the default one (999) - Same behavior as the official image.

**Comment by Gustry** [comment]
Closing for lack of feedback
